version: '2'

services:
  spring-boot-app:
    container_name: mornar-project-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127:0.0.1:8082:8082"
    environment:
      LOGGING_LEVEL_ORG_HIBERNATE.SQL: DEBUG
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cmn4l9md3nmc73f65s0g-a.frankfurt-postgres.render.com:5432/mornar2
      SPRING_DATASOURCE_USERNAME: mornar2_user
      SPRING_DATASOURCE_PASSWORD: egWTQR4hwi9hzVCdpgbjMQZtinABsTX7

