version: '2'

services:
  spring-boot-app:
    container_name: mornar-project-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127:0.0.1:8082:50002"
    environment:
      LOGGING_LEVEL_ORG_HIBERNATE.SQL: DEBUG
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-ckqk001rfc9c7399naeg-a.frankfurt-postgres.render.com/projektmornar
      SPRING_DATASOURCE_USERNAME: projektmornar_user
      SPRING_DATASOURCE_PASSWORD: TcpsQ16EO3aBYwXzJnWEFd0ffiHw7SCx

